OPENAI_API_KEY = "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"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"

HUNTER_API_KEY = "86e708052546bac3bea5176a0a9e1b2ded717ff6"
