OPENAI_API_KEY = "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"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"

HUNTER_API_KEY = "86e708052546bac3bea5176a0a9e1b2ded717ff6"
