OPENAI_API_KEY = "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"

COGNISM_API_KEY = "API-P-05b827c3c69042fabd0992c7d5a351ed"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"
