OPENAI_API_KEY = "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"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"

HUNTER_API_KEY = "86e708052546bac3bea5176a0a9e1b2ded717ff6"
