OPENAI_API_KEY = "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"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"

HUNTER_API_KEY = "86e708052546bac3bea5176a0a9e1b2ded717ff6"
