OPENAI_API_KEY = "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"

COGNISM_API_KEY = "API-P-05b827c3c69042fabd0992c7d5a351ed"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"
