OPENAI_API_KEY = "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"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"

HUNTER_API_KEY = "86e708052546bac3bea5176a0a9e1b2ded717ff6"
