OPENAI_API_KEY = "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"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"

HUNTER_API_KEY = "86e708052546bac3bea5176a0a9e1b2ded717ff6"
