OPENAI_API_KEY = "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"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"

HUNTER_API_KEY = "86e708052546bac3bea5176a0a9e1b2ded717ff6"
