OPENAI_API_KEY = "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"

ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/18435152/20j9p7k/"

HUNTER_API_KEY = "86e708052546bac3bea5176a0a9e1b2ded717ff6"
